### ISSUE TITLE
Error uploading module

### ISSUE THREAD

**Issue by vincentamari** [hatimalam/sugarcrm-sudo-login#1]
Hi, just wanted to test this but during uploading get this error
ZIP Error(0): Status(0): Arhive(upload://sugarcrm-sudo-login-master.zip): Directory(/tmp/q9ierB)

this is using a demo of version 7.6.2.1 Enterprise hosted with Sugar on demand in case that matters?

**Comment by hatimalam** [comment]
Hi Vincent,

This could be zip issue while creating a zip package as I don't think of permission issue on Sugar OD.
I am attaching a zip package (directly install-able via module loader). Please check this and let me know if this is OK.
[sugarcrm-sudo-login.zip](https://github.com/hatimalam/sugarcrm-sudo-login/files/201735/sugarcrm-sudo-login.zip)

**Comment by vincentamari** [comment]
Hi, and thank you for providing the package.
However, now get the following error message when trying to install:

Scanning Package
Installation failed!
The package you are attempting to install does not conform to the policies established within the Sugar Open Cloud

File Issues
Files/view.detail.php
Invalid usage of a function ob_start()

**Comment by hatimalam** [comment]
Hi Vincent,

Sorry, I checked this and found out that ob_start(), ob_get_contents and ob_end_clean functions are from the standard view.detail.php.
As button array is being customized in view.detail.php, I had no other choice than copy-pasting the complete preDisplay function and edited only buttons array. I tried overriding parent::preDisplay but didn't work. You can either try this out in any on-site instance or you can ask Sugar Support to install this file.

**Comment by hatimalam** [comment]
Hi Vincent,

I know, it has been a very long time. But, I had a chance to work on it again and I have resolved that issue now. That means, it is compatible for on-demand installation as well. I am attaching the latest package here (directly installable via module loader). Please try now and let me know your comments.
[sugarcrm-sudo-login-v2.zip](https://github.com/hatimalam/sugarcrm-sudo-login/files/699658/sugarcrm-sudo-login-v2.zip)

Regards,
Hatim Alam

**Comment by hatimalam** [comment]
Latest package - 
[sugarcrm-sudo-login-v2.zip](https://github.com/hatimalam/sugarcrm-sudo-login/files/1083768/sugarcrm-sudo-login-v2.zip)
